version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: dataeng_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data  ## volume is a MUST to maintain persistance
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  minio-data:

networks:
  default:
    name: dataeng
    external: true
